# Generated by Django 4.1.3 on 2022-12-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNueva', '0002_alter_empleado_año_antiguedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='sueldo',
            field=models.IntegerField(),
        ),
    ]
