# Generated by Django 4.1.3 on 2022-12-17 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNueva', '0003_alter_empleado_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nombre_empleado',
            field=models.CharField(default=datetime.datetime(2022, 12, 17, 1, 39, 30, 557382, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre_estudiante',
            field=models.CharField(default=datetime.datetime(2022, 12, 17, 1, 39, 41, 384034, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
