# Generated by Django 4.1.3 on 2022-12-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNueva', '0004_empleado_nombre_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(default=19094562),
            preserve_default=False,
        ),
    ]
